// Generated by the source export. Do not edit.
//
// The CLI names request and response types that are defined with the
// PipeLedger service, which is not part of this repository. They are erased
// when the CLI is built. Each is declared here without its shape so that the
// source type-checks on its own; the service validates every request.

declare module "shared" {
  export type CashFlowCategory = any;
  export type CashFlowTreatment = any;
  export type FinanceCatalogMetricDraftInput = any;
  export type PublicationCertification = any;
  export type ReportRecipe = any;
  export type SourceDataRecency = any;
  export type TaxonomyMappingUpdate = any;
  export type UnitVoucherUpdateRequestInput = any;
  export type UnitVoucherVoidInput = any;
  export type Whoami = any;
}

declare module "capabilities" {
  export type DrilldownTargetGrain = any;
  export type PlSchemaRequest = any;
  export type PlSchemaResult = any;
}
